"""empty message

Revision ID: 10babf2f5a20
Revises: a23bbf1da62a
Create Date: 2023-10-16 17:33:12.915423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10babf2f5a20'
down_revision = 'a23bbf1da62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('singoplace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singoplace',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=True),
    sa.Column('placeid', sa.INTEGER(), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['placeid'], ['place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
