"""empty message

Revision ID: 1dd19e3696fc
Revises: d1bde86fd1a2
Create Date: 2023-09-26 13:23:40.833907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd19e3696fc'
down_revision = 'd1bde86fd1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('type_code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('userlike', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('placeid',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlike', schema=None) as batch_op:
        batch_op.alter_column('placeid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('userid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.alter_column('type_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
