"""empty message

Revision ID: 26004bc530a2
Revises: 
Create Date: 2023-09-26 12:43:12.000287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26004bc530a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typecode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Integer(), nullable=True),
    sa.Column('type_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('star_rating', sa.String(length=64), nullable=True),
    sa.Column('review_total', sa.String(length=64), nullable=True),
    sa.Column('address_si', sa.String(length=64), nullable=False),
    sa.Column('address_gu', sa.String(length=64), nullable=False),
    sa.Column('address_lo', sa.String(length=64), nullable=False),
    sa.Column('address_detail', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.String(length=64), nullable=True),
    sa.Column('lng', sa.String(length=64), nullable=True),
    sa.Column('naver_place_id', sa.String(length=64), nullable=False),
    sa.Column('place_url', sa.String(length=64), nullable=True),
    sa.Column('road_url', sa.String(length=64), nullable=True),
    sa.Column('mon_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('mon_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('tue_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('tue_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('wed_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('wed_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('thu_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('thu_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('fri_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('fri_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('sat_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('sat_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('sun_opening_hours', sa.String(length=64), nullable=True),
    sa.Column('sun_last_order_time', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['type_code'], ['typecode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=False),
    sa.Column('placeid', sa.String(length=64), nullable=False),
    sa.Column('likedate', sa.DateTime(timezone=64), nullable=False),
    sa.ForeignKeyConstraint(['placeid'], ['place.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlike')
    op.drop_table('place')
    op.drop_table('user')
    op.drop_table('typecode')
    # ### end Alembic commands ###
