"""empty message

Revision ID: 38633f288e46
Revises: bced67b3d62a
Create Date: 2023-09-28 19:45:34.132413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38633f288e46'
down_revision = 'bced67b3d62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kakao_road_url', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('kakao_road_url')

    # ### end Alembic commands ###
