"""empty message

Revision ID: a23bbf1da62a
Revises: a15e1da3f421
Create Date: 2023-09-29 14:17:54.912653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23bbf1da62a'
down_revision = 'a15e1da3f421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('singoplace', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('singoplace', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
