"""empty message

Revision ID: bced67b3d62a
Revises: 9440db29a104
Create Date: 2023-09-28 19:43:32.695688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bced67b3d62a'
down_revision = '9440db29a104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naver_road_url', sa.String(length=64), nullable=True))
        batch_op.drop_column('road_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('road_url', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('naver_road_url')

    # ### end Alembic commands ###
