"""empty message

Revision ID: d1bde86fd1a2
Revises: 26004bc530a2
Create Date: 2023-09-26 13:20:30.822894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bde86fd1a2'
down_revision = '26004bc530a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('review_total',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.alter_column('review_total',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=256),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
